version: '3'
services:
  main:
    image: php:apache-buster
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
      - ./api/out:/var/www/html/out
    links:
      - api
  api:
    image: mdpdfizer:latest
    ports:
      - "5000:5000"
    volumes:
      - ./api/:/api
      - ./api/out:/api/out
    working_dir: /api
    command: "gunicorn --bind 0.0.0.0:5000 'main:api'"
