version: '3'
services:
  main:
    image: php:apache-buster
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html:rz
      - ./api/in:/var/www/html/in:w
      - ./api/out:/var/www/html/out:r
  api:
    image: python:latest
    ports:
      - "5000:5000"
    volumes:
      - ./api:/:r
      - ./api/in:/in:w
      - ./api/out:/out:r