version: '3'
services:
  main:
    image: php:apache-buster
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
      - ./api/out:/var/www/html/out
    links:
      - api
  api:
    image: converter-api:latest
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
      - ./api/out:/api/out
    command: "python3 /api/converter-api.py"

